@baseUrl = http://localhost:3333

### Health Check
GET {{baseUrl}}/health

### List Rooms
GET {{baseUrl}}/rooms

### Create room
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de teste",
  "description": "Essa é uma sala de teste"
}
